repos:
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.391
    hooks:
      - id: pyright
        additional_dependencies: ["pydantic", "icalendar", "pytz", "aiohttp", "pytest", "pytest-asyncio"]
