name: Update Calendars

on:
  schedule:
    - cron: "0 4,12,20 * * *"
  workflow_dispatch:
  push:
    branches:
      - master

concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --only main

      - name: Generate Calendars
        run: poetry run israeli-rail-calendar

      - name: Deploy to GitHub Pages branch
        run: |
          mkdir -p ../deploy_tmp
          cp -r web/* ../deploy_tmp/
          cp calendars/*.ics ../deploy_tmp/
          cp calendars/routes.json ../deploy_tmp/

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan gh-pages
          git rm -rf .

          mv ../deploy_tmp/* .

          git add .
          git commit -m "Deploy calendars and Web UI" || echo "No changes to commit"
          git push -f origin gh-pages
